kafka:
  clusters:
    - name: local
      bootstrapServers: localhost:29092
      schemaRegistry: http://localhost:8081
      # schemaRegistryAuth:
      #   username: username
      #   password: password
      #     schemaNameTemplate: "%s-value"
      metrics:
        port: 9997
        type: JMX
